### ISSUE TITLE
Maybe use yaml or hydra to manage all config files

### ISSUE THREAD

**Issue by ak3ra** [SunbirdAI/nmt_training#12]
[Hydra](https://hydra.cc/docs/intro/
)
https://github.com/SunbirdAI/nmt_training/blob/3c1894a13f88d795524ff58081600c26efac1e66/run_simple_evaluation.py#L11

see below;

```python3
# Import required libraries
import hydra
from omegaconf import DictConfig

# Define the function that uses the configuration file
@hydra.main(config_path="config", config_name="my_config")
def my_function(cfg: DictConfig) -> None:
    # Access the configuration values using dot notation
    print(f"Running with batch size = {cfg.training.batch_size}")

# Call the function
if __name__ == "__main__":
    my_function()

```

Here's how the yaml file could look like:

```yaml

training:
  batch_size: 32
  learning_rate: 0.001
  epochs: 10
data:
  train_dir: /path/to/train/data
  val_dir: /path/to/validation/data


```
